name: Simple CI Pipeline

on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to 'main'
  pull_request:
    branches:
      - main  # Runs on pull request events to 'main'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out the repository

      - name: Print Hello World
        run: echo "Hello, World! 🚀 CI Pipeline is running!"
              ls -ltr
      - name: Run a Simple Test
        run: echo "Running tests..." && sleep 2 && echo "✅ Tests passed!"
