name: Multi-Job CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs workflow on push to main branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    name: "Build Project"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: echo "Installing dependencies..." && sleep 2

      - name: Build Project
        run: echo "Building project..." && sleep 2

  test:
    name: "Run Tests"
    needs: build  # Runs only after 'build' job completes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]  # Run tests on multiple Node.js versions
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        run: echo "Running tests on Node.js ${{ matrix.node-version }}..." && sleep 2

  deploy:
    name: "Deploy to Production"
    needs: test  # Runs only after 'test' job completes successfully
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy from main branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: echo "Deploying application to production..." && sleep 2

      - name: Send Deployment Notification
        run: echo "✅ Deployment successful!"
